"""The first migration this project has ever had, and it is the user model.

That order is not an accident and cannot be rearranged later. Django resolves
AUTH_USER_MODEL through the migration graph, so a project that runs any other
app's migrations first has already written a dependency on whatever user model
was in force at the time. This one runs before `admin`, `auth` gets pulled in
as a dependency rather than a predecessor, and every app still to be written
-- billing, catalog, instances -- will point at `accounts.Account` from its own
first migration.

`email` and `handle` are both unique, and both are lowercased by the model
before it is saved. The uniqueness constraint is enforced on the stored value,
so the lowercasing has to happen first or `Ada@example.com` and
`ada@example.com` are two accounts sharing one mailbox -- see the note on
`SignUpForm.clean_email`, which lowercases before the form's own uniqueness
check for the same reason.

Generated by Django 6.1.1, then documented; the operations are unedited.
"""


import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used to sign in. Never shown to anybody else.', max_length=254, unique=True)),
                ('handle', models.SlugField(help_text='Your public name in addresses: milepost.example/people/you.', max_length=30, unique=True, validators=[accounts.models.validate_handle])),
                ('display_name', models.CharField(blank=True, help_text='What people see. Your handle is used if you leave this blank.', max_length=60)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['handle'],
            },
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
