# Generated by Django 6.1.1 on 2026-09-14 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_authorizationcode'),
        ('catalog', '0004_household_on_acquisitions_and_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PUBLISHED', 'Published a plan'), ('WIDELY_USED', 'Widely used'), ('WELL_REVIEWED', 'Well reviewed'), ('SUSTAINED', 'Still going a year on'), ('FOUNDING', 'Founding contributor')], max_length=13)),
                ('reason', models.TextField()),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_granted', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='catalog.listing')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('organisation__isnull', True)), models.Q(('account__isnull', True), ('organisation__isnull', False)), _connector='OR'), name='award_has_exactly_one_subject'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='award_reason_is_not_blank'), models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('listing__isnull', True)), fields=('account', 'kind'), name='one_overall_award_per_account_per_kind'), models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('listing__isnull', False)), fields=('account', 'kind', 'listing'), name='one_award_per_account_per_kind_per_listing'), models.UniqueConstraint(condition=models.Q(('listing__isnull', True), ('organisation__isnull', False)), fields=('organisation', 'kind'), name='one_overall_award_per_organisation_per_kind'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False), ('organisation__isnull', False)), fields=('organisation', 'kind', 'listing'), name='one_award_per_organisation_per_kind_per_listing')],
            },
        ),
    ]
