"""Regenerate the machine channel's signing vectors.

THIS IS NOT A MAINTENANCE CHORE, AND THE COMMAND EXISTS TO MAKE THAT VISIBLE
============================================================================
`instances/machine_vectors.json` is the wire contract. Both this project and
`homeschool-lms` assert that their own signer reproduces every signature in it,
which is what stops two independent implementations of one HMAC rule from
drifting apart in the one place drift cannot be noticed: an instance in the
field, months behind, getting a 403 nobody can reproduce.

So running this command and committing the result is a statement that **the
wire format changed**. Every deployed instance would have to be upgraded to
speak the new one, and §A says plainly that compatibility here "CANNOT be
redeployed on your schedule".

If a vector test is failing, the overwhelmingly likely cause is that `auth.sign`
or `auth.string_to_sign` changed by accident. Regenerating makes the test pass
and the field break. Fix the signer instead.

The command is here rather than the file being hand-written because the cases
are chosen prose plus a mechanical answer, and hand-computing twelve HMACs is
how a typo becomes a contract.

WHY THE COMMITTED FILE WAS NOT GENERATED BY THIS COMMAND
=========================================================
The first version was produced by a separate reading of `auth.py`'s prose,
deliberately, so that the first run of `MachineVectorTests` compared two
independent implementations rather than comparing `auth.sign` to itself. That
run is the only time the check did real work against a fresh reading; from here
on it guards against change rather than against a first-time mistake.

Re-running this command replaces that property with a self-consistent file.
That is fine and is the point -- but it is why the original was not made this
way, and why the answer to a failing vector is never "regenerate".
"""

import base64
import json
from pathlib import Path

from django.core.management.base import BaseCommand

from instances import auth

VECTORS = Path(__file__).resolve().parents[2] / 'machine_vectors.json'


class Command(BaseCommand):
    help = 'Rewrite instances/machine_vectors.json from the current signer.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--yes-the-wire-format-changed',
            action='store_true',
            help=(
                'Required. Regenerating is a breaking change to a channel '
                'deployed instances cannot be made to re-speak; the flag is '
                'here so nobody does it to quiet a failing test.'
            ),
        )

    def handle(self, *args, **options):
        if not options['yes_the_wire_format_changed']:
            self.stderr.write(
                'Refusing. This file is the wire contract for every deployed '
                'instance, and a failing vector almost always means the '
                'signer changed by accident rather than that the contract '
                'moved. Read the module docstring, then pass '
                '--yes-the-wire-format-changed if you still mean it.'
            )
            return

        document = json.loads(VECTORS.read_text(encoding='utf-8'))

        for case in document['cases']:
            body = base64.b64decode(case['body_base64'])
            case['string_to_sign'] = auth.string_to_sign(
                case['method'], case['path'], case['timestamp'],
                case['nonce'], body,
            )
            case['signature'] = auth.sign(
                case['key'], case['method'], case['path'],
                case['timestamp'], case['nonce'], body,
            )

        VECTORS.write_text(
            json.dumps(document, indent=2, ensure_ascii=False) + '\n',
            encoding='utf-8',
        )
        self.stdout.write(
            f'Rewrote {len(document["cases"])} vectors. '
            'Copy the file to homeschool-lms in the same commit, or the two '
            'halves of this channel now disagree.'
        )
